# Generated by Django 3.2.12 on 2022-04-28 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0152_flatproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatproduct',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
