# Generated by Django 3.2.12 on 2022-04-28 03:48

from django.db import migrations
import django_measurement.models
import measurement.measures.mass


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0153_flatproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatproduct',
            name='weight',
            field=django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.mass.Mass, null=True),
        ),
    ]
