# Generated by Django 3.2.12 on 2022-04-29 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0154_alter_flatproduct_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
