# Generated by Django 3.2.12 on 2022-04-29 04:25

from django.db import migrations


def migrate_data_from_product_to_flatproduct(apps, schema_editor):

    FlatProduct = apps.get_model("product", "FlatProduct")
    ProductVariant = apps.get_model("product", "ProductVariant")
    for product_variant in ProductVariant.objects.iterator():

        flat_product_input = {
            "name": product_variant.product.name,
            "description": product_variant.product.description,
            "sku": product_variant.sku,
            "weight": product_variant.weight,
            "product_id": product_variant.product_id
        }
        FlatProduct.objects.create(**flat_product_input)


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0154_alter_flatproduct_weight'),
    ]

    operations = [
        migrations.RunPython(migrate_data_from_product_to_flatproduct)
    ]
