# Generated by Django 3.2.12 on 2022-04-29 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0155_alter_flatproduct_product'),
        ('product', '0156_auto_20220429_0641'),
    ]

    operations = [
    ]
