# Generated by Django 3.2.12 on 2022-05-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0116_auto_20211207_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='original_sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
