# Generated by Django 3.2.12 on 2022-04-20 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0116_auto_20211207_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='requested_shipment_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
