# Generated by Django 3.2.12 on 2022-04-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0117_order_requested_shipment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='requested_shipment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
